# -*- coding: utf-8 -*-
"""Testing task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CxT0R9WQQbYHxDctrUAhvJgH3klWDXHj
"""

!pip install ultralytics

from google.colab import drive

drive.mount('/content/drive')

import zipfile

zip_path = "/content/drive/MyDrive/Testing_task.v2i.yolov11.zip"

extract_path= "/content/dataset"

with zipfile.ZipFile(zip_path, mode = "r") as zip_link:
  zip_link.extractall(extract_path)

from ultralytics import YOLO

model1 = YOLO("yolo11n.pt")
model2 = YOLO("yolo11s.pt")
model3 = YOLO("yolo11m.pt")
model4 = YOLO("yolo11l.pt")
model5 = YOLO("yolo11x.pt")

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(f"тип устройства: {device}")

model1.train(data='/content/dataset/data.yaml', epochs = 50, imgsz = 640)

model2.train(data='/content/dataset/data.yaml', epochs = 50, imgsz = 640)

model3.train(data='/content/dataset/data.yaml', epochs = 50, imgsz = 640)

model4.train(data='/content/dataset/data.yaml', epochs = 50, imgsz = 640)

# загружаем обученную модель (best.pt)
model1 = YOLO('runs/detect/train/weights/best.pt')

metrics1 = model1.val(data = '/content/dataset/data.yaml',
           project='/content/runs/detect',  # базовая папка
           name='res1',                   # имя подпапки
           exist_ok=True,
           save_json=True)

model2 = YOLO('runs/detect/train2/weights/best.pt')
metrics2 = model2.val(data = '/content/dataset/data.yaml',
           project='/content/runs/detect',  # базовая папка
           name='res2',                   # имя подпапки
           exist_ok=True,
           save_json=True)

model3 = YOLO('runs/detect/train3/weights/best.pt')
metrics3 = model3.val(data = '/content/dataset/data.yaml',
           project='/content/runs/detect',  # базовая папка
           name='res3',                   # имя подпапки
           exist_ok=True,
           save_json=True)

model4 = YOLO('runs/detect/train4/weights/best.pt')
metrics4 = model4.val(data = '/content/dataset/data.yaml',
           project='/content/runs/detect',  # базовая папка
           name='res4',                   # имя подпапки
           exist_ok=True,
           save_json=True)

import numpy as np
print("Metrics for 1st model")
print(f"Precision: {np.mean(metrics1.box.p):.4f}")
print(f"Recall: {np.mean(metrics1.box.r):.4f}")
print(f"mAP0.5: {metrics1.box.map50:.4f}")
print(f"mAP0.5-0.95: {metrics1.box.map:.4f}")

print("Metrics for 2nd model")
print(f"Precision: {np.mean(metrics2.box.p):.4f}")
print(f"Recall: {np.mean(metrics2.box.r):.4f}")
print(f"mAP0.5: {metrics2.box.map50:.4f}")
print(f"mAP0.5-0.95: {metrics2.box.map:.4f}")

print("Metrics for 3rd model")
print(f"Precision: {np.mean(metrics3.box.p):.4f}")
print(f"Recall: {np.mean(metrics3.box.r):.4f}")
print(f"mAP0.5: {metrics3.box.map50:.4f}")
print(f"mAP0.5-0.95: {metrics3.box.map:.4f}")

print("Metrics for 4th model")
print(f"Precision: {np.mean(metrics4.box.p):.4f}")
print(f"Recall: {np.mean(metrics4.box.r):.4f}")
print(f"mAP0.5: {metrics4.box.map50:.4f}")
print(f"mAP0.5-0.95: {metrics4.box.map:.4f}")

from google.colab import files
uploaded = files.upload()  # загрузи video.mp4

model3.predict(source = "/content/drive/MyDrive/VID_20250620_165014.mp4",
               save=True,
               save_txt=True,
               project='/content/runs/detect',
               name='testing_video',
               exist_ok=True)